### ISSUE TITLE
AMP switching to non AMP on page switch

### ISSUE THREAD

**Issue by J05HI** [juliomrqz/website#215]
Hello @juliomrqz 
I found another bug.
If I visit your AMP site like [https://marquez.co/amp](https://marquez.co/amp) and navigate to another page it switches back to non AMP. Shouldn't it call the new page with "/amp/" too?
Have a great weekend!

**Comment by juliomrqz** [comment]
Hello @J05HI. 

That behavior is intentional.  AMP is very useful to use it as a second version of your site that helps you improve SEO, but it is very restrictive when defining the interactivity of your site, for that the main version of the site, in this case, uses Vue.js.  In short, your Vue.js site is the main version and the AMP pages are an extra push for better SEO.

**Comment by J05HI** [comment]
@juliomrqz 
Okay so (just) SEO 😉 
Thank you very much!

**Comment by J05HI** [comment]
@juliomrqz 
A second small question:
How does google know that the AMP page exists? It isn't listed in the sitemap. Does it just check for "<domain>/amp/" like it does for sitemaps?

**Comment by juliomrqz** [comment]
Google knows that in two ways:

1.- [required] a special meta tag in the page: https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/discovery/
2.- [optional] a reference in the sitemap

You can easily check those for this project 🤓
